# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1e630b0e-9258-4e51-bacd-c8ad1f1e9b99";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D84C-4D49";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/data/SSD1" =
    { device = "/dev/disk/by-uuid/3b49cf0f-dc8a-4d07-b53c-d2338df484e5";
      fsType = "ext4";
    };

  fileSystems."/data/HDD1" =
    { device = "/dev/disk/by-uuid/5c6490ba-6e5d-464b-974d-207cbfe472df";
      fsType = "ext4";
    };

  fileSystems."/data/SSD2" =
    { device = "/dev/disk/by-uuid/c48fc144-8c31-4ddc-9d66-d13891b3c0a7";
      fsType = "ext4";
    };

  systemd.tmpfiles.rules = [
    "d /data/SSD1 0755 gustl users -"
    "d /data/SSD2 0755 gustl users -"
    "d /data/HDD1 0755 gustl users -"
  ];


  swapDevices =
    [ { device = "/dev/disk/by-uuid/fc4623e8-4fc7-44f6-a45e-35480e8108a5"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp34s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
