# Auto-generated using compose2nix v0.3.3-pre.
{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."n8n-n8n" = {
    image = "docker.n8n.io/n8nio/n8n";
    environment = {
      "GENERIC_TIMEZONE" = "Europe/Berlin";
      "N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS" = "true";
      "N8N_HOST" = "0.0.0.0";
      "N8N_PORT" = "5678";
      "N8N_PROTOCOL" = "http";
      "NODE_ENV" = "production";
      "TZ" = "Europe/Berlin";
    };
    volumes = [
      "/data/SSD1/n8n/local-files:/files:rw"
      "/data/SSD1/n8n/n8n_data:/home/node/.n8n:rw"
    ];
    ports = [
      "5678:5678/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=n8n"
      "--network=n8n_default"
    ];
  };
  systemd.services."podman-n8n-n8n" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-n8n_default.service"
    ];
    requires = [
      "podman-network-n8n_default.service"
    ];
    partOf = [
      "podman-compose-n8n-root.target"
    ];
    wantedBy = [
      "podman-compose-n8n-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-n8n_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f n8n_default";
    };
    script = ''
      podman network inspect n8n_default || podman network create n8n_default
    '';
    partOf = [ "podman-compose-n8n-root.target" ];
    wantedBy = [ "podman-compose-n8n-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-n8n-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
